## Neural Networks

In [1]:
import numpy as np

In [24]:
x_1 = 3
x_2 = 14
x = [3, 14]

In [25]:
W = np.array([[1,0,-1], [0, 1, -1], [-1, 0, -1], [0, -1, -1]])

In [26]:
W

array([[ 1,  0, -1],
       [ 0,  1, -1],
       [-1,  0, -1],
       [ 0, -1, -1]])

In [27]:
V = np.array([[1, 1, 1, 1, 0], [-1, -1, -1, -1, 2]])

In [28]:
V

array([[ 1,  1,  1,  1,  0],
       [-1, -1, -1, -1,  2]])

In [57]:
def z_func(x, W):
    z_list = []
    for i in range(W.shape[0]):
        z_list.append(np.maximum((x[0] * W[i][0] + x[1] * W[i][1] + W[i][2]), 0))
    return z

In [58]:
W.shape[0]

4

In [59]:
# z_1, z_2, z_3, z_4 = z_func(x, W)
z = z_func(x, W)
z

[2, 13, 0, 0]

In [60]:
def v_func(z, V):
    v_list = []
    for i in range(V.shape[0]):
        v_list.append(np.maximum((z[0] * V[i][0] + z[1] * V[i][1] + z[2] * V[i][2] + z[3] * V[i][3] + V[i][4]), 0))
    return v_list

In [62]:
u_1, u_2 = v_func(z, V)

In [64]:
o_1 = np.exp(u_1)/(np.exp(u_1)+ np.exp(u_2))
o_2 = np.exp(u_2)/(np.exp(u_1)+ np.exp(u_2))

In [65]:
o_1

0.9999996940977731

In [78]:
o_2

3.059022269256247e-07

In [68]:
o_2

3.059022269256247e-07

In [69]:
np.exp(0)/(np.exp(0)+ np.exp(2))

0.11920292202211755

In [70]:
np.exp(1)/(np.exp(1)+ np.exp(1))

0.5

In [77]:
np.exp(3)/(np.exp(3)+ np.exp(0))

0.9525741268224333

In [76]:
np.exp(-1)

0.36787944117144233

In [79]:
o_1_beta_3 = np.exp(*u_1)/(3*np.exp(u_1)+ np.exp(3*u_2))
o_2_beta_3 = np.exp(3*u_2)/(3*np.exp(u_1)+ np.exp(3*u_2))

In [80]:
o_1_beta_3

3562157830617.372

In [82]:
o_2_beta_3>=1/1000

False

In [83]:
o_1_beta_1 = np.exp(0)/(np.exp(0)+ np.exp(0))
o_2_beta_1 = np.exp()/(np.exp(0)+ np.exp(2))

In [85]:
o_2_beta_1 >=1/1000

True

## LSTM

In [457]:
def ft (W_fh, h_t1, W_fx, x_t, b_f):
    x = W_fh * h_t1 + W_fx * x_t + b_f
    if x >= 1:
        return 1
    elif x <= -1:
        return 0
    return 1/(1+np.exp(-x))

def it (W_ih, h_t1, W_ix, x_t, b_i):
    x = W_ih * h_t1 +W_ix * x_t + b_i
    if x >= 1:
        return 1
    elif x <= -1:
        return 0
    return 1/(1+np.exp(-x))

def ot (W_oh, h_t1, W_ox, x_t, b_o):
    x = W_oh * h_t1 +W_ox * x_t + b_o
    if x >= 1:
        return 1
    elif x <= -1:
        return 0
    return 1/(1+np.exp(-x))

def ct (ft, c_t1, it, W_ch, h_t1, W_cx, x_t, b_c):
    x = W_ch * h_t1 + W_cx * x_t + b_c
#     print("ft: ", ft, "\nct: ", c_t1)
    tanh_x = (np.exp(x)-np.exp(-x))/((np.exp(x)+np.exp(-x)))
#     print("x: ", x ,"\ntanh: ", tanh_x)
    if x >= 1:
        tanh_x = 1
    elif x <= -1:
        tanh_x = -1
    x_one = np.dot(ft, c_t1)
    x_two = np.dot(it, tanh_x)
    return x_one + x_two

def ht (ot, ct):
    tanh_x = (np.exp(ct)-np.exp(-ct))/((np.exp(ct)+np.exp(-ct)))
    print("tanh: ", tanh_x)
    print("ct: ", ct)
#     if ct >= 1:
#         tanh_x = 1
#     elif ct <= -1:
#         tanh_x = -1
    return np.dot(ot, tanh_x)

In [458]:
W_fh = W_fx = W_ih = W_oh = 0
W_ix = W_ox = 100
W_ch = -100
W_cx = 50
b_o = b_c = 0
b_i = 100
b_f = -100
h_t1 = 0
c_t1 = 0
x_t = [0,0,1,1,1,0]

In [459]:
ft_list = []
for i in x_t:
    ft_list.append(ft(W_fh, h_t1, W_fx, i, b_f))

In [460]:
ft_list

[0, 0, 0, 0, 0, 0]

In [461]:
it_list = []
for i in x_t:
    it_list.append(it(W_ih, h_t1, W_ix, i, b_i))

In [462]:
it_list

[1, 1, 1, 1, 1, 1]

In [463]:
ot_list = []
for i in x_t:
    ot_list.append(ot(W_oh, h_t1, W_ox, i, b_o))

In [464]:
ot_list

[0.5, 0.5, 1, 1, 1, 0.5]

In [465]:
ct_list = []
for i in x_t:
    ct_list.append(ct(ft_list, c_t1, it_list, W_ch, h_t1, W_cx, i, b_c))

In [466]:
ct_list

[array([0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0.]),
 array([1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1]),
 array([0., 0., 0., 0., 0., 0.])]

In [467]:
ht_list = []
for i in range(len(ct_list)):
    ht_list.append(ht(ot_list[i], ct_list[i]))

tanh:  [0. 0. 0. 0. 0. 0.]
ct:  [0. 0. 0. 0. 0. 0.]
tanh:  [0. 0. 0. 0. 0. 0.]
ct:  [0. 0. 0. 0. 0. 0.]
tanh:  [0.76159416 0.76159416 0.76159416 0.76159416 0.76159416 0.76159416]
ct:  [1 1 1 1 1 1]
tanh:  [0.76159416 0.76159416 0.76159416 0.76159416 0.76159416 0.76159416]
ct:  [1 1 1 1 1 1]
tanh:  [0.76159416 0.76159416 0.76159416 0.76159416 0.76159416 0.76159416]
ct:  [1 1 1 1 1 1]
tanh:  [0. 0. 0. 0. 0. 0.]
ct:  [0. 0. 0. 0. 0. 0.]


In [468]:
ht_list

[array([0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0.]),
 array([0.76159416, 0.76159416, 0.76159416, 0.76159416, 0.76159416,
        0.76159416]),
 array([0.76159416, 0.76159416, 0.76159416, 0.76159416, 0.76159416,
        0.76159416]),
 array([0.76159416, 0.76159416, 0.76159416, 0.76159416, 0.76159416,
        0.76159416]),
 array([0., 0., 0., 0., 0., 0.])]

In [445]:
len(ct_list)

6

In [403]:
15*np.exp(30*0.01+2)/(np.exp(15*0.01+1) +1)**3

2.0809165621704557

In [399]:
c = 1/2*(sigma-1)**2

In [400]:
c

0.3342140120616554

In [401]:
np.e

2.718281828459045

In [404]:
-(3*np.exp(3*(-5)/100+1))/(100*(np.exp(3*(-5)/100+1))**3)

-0.00548050572158204

In [408]:
w_1 = 0.01
w_2 = -5
b = -1
t = 1
x = 3

z_1 = w_1 * x
a_1 = np.maximum(0, z_1)
z_2 = w_2 * a_1 + b
y = 1/(1+np.exp(-z_2))
c = 1/2*(y - t)**2


In [413]:
a_1

0.03

In [409]:
c

0.28842841648243966

In [410]:
a_1

0.03

In [411]:
z_2

-1.15

In [412]:
y

0.24048908305088898

In [427]:
derivative_w2 = -(3*np.exp(3*w_2/100+2))/(100*(np.exp(3*w_2/100)+np.e)**3)

In [428]:
derivative_w2

-0.00416183312434091

In [418]:
w_1*w_2*x

-0.15000000000000002

In [429]:
derivative_b = -np.exp(b+3/10)/(np.exp(b)+ np.exp(3/20))**3

In [430]:
derivative_b

-0.13872777081136367

In [426]:
w_1*x

0.03