In [4]:
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append("..")
sys.path.insert(1, 'D:\EDX Courses\MITx-6.86x\Project_2_data')
import utils
from utils import *
sys.path.insert(1, 'D:\EDX Courses\MITx-6.86x\Project_2_data\part1')
import linear_regression
from linear_regression import *
from svm import *
from softmax import *
from features import *
from kernel import *

In [46]:
def closed_form(X, Y, lambda_factor):
    """
    Computes the closed form solution of linear regression with L2 regularization

    Args:
        X - (n, d + 1) NumPy array (n datapoints each with d features plus the bias feature in the first dimension)
        Y - (n, ) NumPy array containing the labels (a number from 0-9) for each
            data point
        lambda_factor - the regularization constant (scalar)
    Returns:
        theta - (d + 1, ) NumPy array containing the weights of linear regression. Note that theta[0]
        represents the y-axis intercept of the model and therefore X[0] = 1
    """
    # YOUR CODE HERE
    
    iden_mat = np.identity(X.shape[1])
    inversible = np.matmul(X.T, X) - (-lambda_factor) * iden_mat
    inverse = np.linalg.inv(inversible)
    return (np.matmul(inverse, np.matmul(X.T,Y)))
    raise NotImplementedError

In [47]:
def run_linear_regression_on_MNIST(lambda_factor=1):
    """
    Trains linear regression, classifies test data, computes test error on test set

    Returns:
        Final test error
    """
    train_x, train_y, test_x, test_y = get_MNIST_data()
    train_x_bias = np.hstack([np.ones([train_x.shape[0], 1]), train_x])
    test_x_bias = np.hstack([np.ones([test_x.shape[0], 1]), test_x])
    theta = closed_form(train_x_bias, train_y, lambda_factor)
    test_error = compute_test_error_linear(test_x_bias, test_y, theta)
    return test_error

In [4]:
# Don't run this until the relevant functions in linear_regression.py have been fully implemented.
print('Linear Regression test_error =', run_linear_regression_on_MNIST(lambda_factor=1))

NameError: name 'get_MNIST_data' is not defined

In [5]:
# 	 θ=(XTX+λI)−1XTY 	 
import numpy as np
X = np.array([[1,2,3],[2,3,4]])
i = np.identity(X.shape[1])

In [26]:
inversible = np.matmul(X.T, X) - (-1)*i
inverse = np.linalg.inv(inversible)

array([[ 0.8, -0.2, -0.2],
       [-0.2,  0.7, -0.4],
       [-0.2, -0.4,  0.4]])

In [25]:
test = np.array([[3,-4], [2,-5]])
np.linalg.inv(test)

array([[ 0.71428571, -0.57142857],
       [ 0.28571429, -0.42857143]])

In [14]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
X.T  np.array([1,2])

array([[1, 4],
       [2, 6],
       [3, 8]])

In [48]:
X = np.array([[0.08306065, 0.40367245],
 [0.73721212, 0.1446548 ],
 [0.37854212, 0.91848412],
 [0.34735579, 0.92967347],
 [0.58275768, 0.02878153],
 [0.11577078, 0.3793189 ],
 [0.49626992, 0.03433923],
 [0.93620684, 0.81767935],
 [0.50209705, 0.76204725],
 [0.71287984, 0.12056536],
 [0.8482472,  0.63871636],
 [0.89746806, 0.60944071],
 [0.80312304, 0.39808585],
 [0.17187538, 0.96388742],
 [0.36947729, 0.70868798],
 [0.54650151, 0.92196146],
 [0.04545365, 0.32840425],
 [0.20310255, 0.77202396]])
Y = np.array([0.47448298, 0.24419894, 0.02347939, 0.69281014, 0.38118102, 0.30887115,
 0.04431094, 0.49541117, 0.9945525,  0.49814587, 0.981581,   0.20000342,
 0.02283484, 0.35575137, 0.03563995, 0.27161267, 0.13116319, 0.87779631])
lambda_factor = 0.7052750700565534

In [49]:
closed_form(X, Y, lambda_factor)

array([0.25953114, 0.39594302])

In [1]:
def compute_probabilities(X, theta, temp_parameter):
    """
    Computes, for each datapoint X[i], the probability that X[i] is labeled as j
    for j = 0, 1, ..., k-1

    Args:
        X - (n, d) NumPy array (n datapoints each with d features)
        theta - (k, d) NumPy array, where row j represents the parameters of our model for label j
        temp_parameter - the temperature parameter of softmax function (scalar)
    Returns:
        H - (k, n) NumPy array, where each entry H[j][i] is the probability that X[i] is labeled as j
    """
    #YOUR CODE HERE
    raise NotImplementedError